Pull request guidelines for SUGCON redesign team
Sitecore/XM-Cloud-Introduction pull request #313
Opened 2024-01-22 17:48 UTC by cheeto-bandito

## Description / Motivation

We've got a multi-disciplinary team working on the SUGCON redesign project.  I want to get some guidelines in place for how we will be submitting and reviewing changes to this code base.  While the immediate intent of this documentation is for the SUGCON redesign, it should be applicable for the rest of the code base as well.

## How Has This Been Tested?

This is documentation only.  Will be reviewing with the larger team during standup.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read the Contributing guide.
- [x] My code/comments/docs fully adhere to the Code of Conduct.
- [ ] My change is a code change.
- [x] My change is a documentation change and there are NO other updates required.

2024-01-23 00:49 UTC, robearlam requested changes
Looks good, a couple of small amendments requested.

Could you also link to this document from within the content in the CONTRIBUTNG.md as they're related.

2024-01-23 00:49 UTC, robearlam commented on docs/PULL_REQUESTS.md
> +- Merging a pull request is the responsibility of the person who opened the PR. Why? There may be additional tasks such as deploying or updating a tag.
This is not always the case for this repo, the responsibility will lie with members of the Developer Relations team at Sitecore. A lot of the PR's are submitted by the community and they either will not have permission to merge, or at least wont have access to the back-end system should the merge trigger a deploy,

2024-01-23 00:49 UTC, robearlam commented on docs/PULL_REQUESTS.md
> +  - :thought_balloon: - A comment or observation that will not prevent the PR from being approved.
I dont think we need this, there aren't too many PR's being submitted/reviewed that we need to categorise this way.

2024-01-24 22:09 UTC, lovesitecore approved these changes

2024-01-24 22:11 UTC, merged