Create people grid component and person datasource
Sitecore/XM-Cloud-Introduction pull request #352
Opened 2024-02-14 21:13 UTC by ericsanner

https://trello.com/c/m9B3AaET/31-create-featured-speaker-component

![image](https://github.com/Sitecore/XM-Cloud-Introduction/assets/21204526/21c7b678-a7dc-43bd-ab29-12e2024ecc1f)

![image](https://github.com/Sitecore/XM-Cloud-Introduction/assets/21204526/6eb46ad3-1bc5-4bb7-8c60-eed519a06ae1)

## Description / Motivation

1. Added a Person Datasource template
2. Added a People Grid datasource template and rendering

This component is flexible and can suit multiple needs on the site.  People can later be linked to sessions (which can be linked to events).  The people grid component has rendering parameters that allow for

1. Number of columns
2. Background color (paintbucket styles)
3. Optional link to person's bio
4. Optional links to social urls

## How Has This Been Tested?

1. Mobile, tablet and desktop
2. With and without the background style
3. With and without each of the content fields
4. With and without the link to social sites
5. Different numbers of columns

The link to biography was not tested, as that will come in a future story.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read the Contributing guide.
- [x] My code/comments/docs fully adhere to the Code of Conduct.
- [x] My change is a code change.
- [ ] My change is a documentation change and there are NO other updates required.

2024-02-15 12:28 UTC, lovesitecore commented on src/Project/Sugcon2024/items/PlaceholderSettings/Sugcon2024/List Components.yml
All about this component should be part of the Speaker Module. Ideally the Component is named as provided in the Requirements including the field names. I see the aspect of reusing this component but all the required displays of other people such as Organizers are different.

2024-02-15 12:32 UTC, lovesitecore commented on src/Project/Sugcon2024/items/Templates/Sugcon2024/Basic Components/Person/Content/SocialLink1.yml
This should be used with dedicated Social Network. Please Name LinkedIn or Twitter or so. We might associate this with Icons. And they should be always displayed in order.

2024-02-15 12:40 UTC, lovesitecore requested changes
The Items are not consitantly using the same module. You started using the Basic Components Module. I do see a point putting it there when this becomes something more generic. But the display of other person related data is different and also business wise different. So I personally would separate these out. Just have a Speaker Template and a Featured Speaker Component. You could inherit fields to the Speaker Template from a Person Base Template. But this could be a bit overengineered. We can discuss this in todays call.

2024-02-15 19:40 UTC, ericsanner commented on src/Project/Sugcon2024/items/PlaceholderSettings/Sugcon2024/List Components.yml
As discussed on standup, this component can handle all of the uses cases for speakers, featured speakers and organizers.

2024-02-15 19:41 UTC, ericsanner commented on src/Project/Sugcon2024/items/Templates/Sugcon2024/Basic Components/Person/Content/SocialLink1.yml
I have renamed the social links to linkedin and twitter.  Should the twitter link be called "X"?

2024-02-16 14:57 UTC, lovesitecore approved these changes

2024-02-16 14:57 UTC, merged