Migrate repository to match new Starter Kit structure
Sitecore/XM-Cloud-Introduction pull request #481
Opened 2024-09-18 01:46 UTC by robearlam

This PR will update the structure of the repo to match the new default structure defined in the XMC starter kits. It will also change the repo to match FED-First development,  again matching the XMC Starter Kit funcitonality.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] I have read the Contributing guide.
- [x] My code/comments/docs fully adhere to the Code of Conduct.
- [x] My change is a code change.
- [ ] My change is a documentation change and there are NO other updates required.

Closes #480

2024-09-20 09:50 UTC, sc-ivanlieckens requested changes

2024-09-20 09:50 UTC, sc-ivanlieckens commented on docker/build/cm/templates/import-templates.ps1
> -param(
We no longer need this one?

2024-09-20 09:50 UTC, sc-ivanlieckens commented on docker/build/rendering/Development.ps1
> -# Homemade dotnet "watch" script, watches the deploy folder for changes to assembly files.
We stop using the "custom dotnet watch"?

2024-09-20 09:50 UTC, sc-ivanlieckens commented on README.md
> +To run the MVP site you will need to populate the `./headapps/MvpSite/Mvp.Project.MvpSite.Rendering/appsettings.Development.json`. You will need to provide the Sitecore instance, and Okta sections, i
I think it's not good to have people adjust this since it's a source controlled file. Can we explain how to do this with environment variables? It invites mistakes where secrets get committed to the repo.

2024-09-20 09:50 UTC, sc-ivanlieckens commented on README.md
> +To run the MVP site you will need to populate the `./headapps/MvpSite/Mvp.Project.MvpSite.Rendering/appsettings.Development.json`. You will need to provide the Sitecore instance, and Okta sections, i
I think it's not good to have people adjust this since it's a source controlled file. Can we explain how to do this with environment variables? It invites mistakes where secrets get committed to the repo.

2024-09-22 21:58 UTC, robearlam commented on docker/build/cm/templates/import-templates.ps1
> -param(
We dont use this in our scripts

2024-09-22 21:58 UTC, robearlam commented on docker/build/rendering/Development.ps1
> -# Homemade dotnet "watch" script, watches the deploy folder for changes to assembly files.
Yeah, I migrated it to match the `dotnet watch` approach you create for the ASP.NET Core StarterKit

2024-09-23 13:48 UTC, IvanLieckens commented on README.md
> +To run the MVP site you will need to populate the `./headapps/MvpSite/Mvp.Project.MvpSite.Rendering/appsettings.Development.json`. You will need to provide the Sitecore instance, and Okta sections, i
Srry this thread was an accidental double post due to the slowness of the review system. The changeset is too large for github to handle 😆

2024-09-25 04:19 UTC, robearlam commented on README.md
> +To run the MVP site you will need to populate the `./headapps/MvpSite/Mvp.Project.MvpSite.Rendering/appsettings.Development.json`. You will need to provide the Sitecore instance, and Okta sections, i
Yeah I hear you, but .NET doesn't work with `.env` files OOTB, so we'd need to write this functionality into the configuration parsing on app start?

2024-09-25 06:55 UTC, robearlam commented on README.md
> +To run the MVP site you will need to populate the `./headapps/MvpSite/Mvp.Project.MvpSite.Rendering/appsettings.Development.json`. You will need to provide the Sitecore instance, and Okta sections, i
Removed appsettings.Development.json and excluded it in the .gitignore. Updated the readme to have the developert create and populate that file.

2024-09-25 06:59 UTC, sc-ivanlieckens approved these changes

2024-09-25 23:58 UTC, merged